# Generated by Django 4.2.8 on 2023-12-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiamiento_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='proveeder',
            new_name='proveedor',
        ),
    ]
